name: 'Bytebase Login'
description: 'Login to your Bytebase service'
inputs:
  bytebase-url:
    description: "The Bytebase instance URL, should be the Bytebase external URL"
    required: true
  api-version:
    description: "Bytebase API version"
    required: false
    default: "v1"
  service-key:
    description: "The Bytebase service account key"
    required: true
  service-secret:
    description: "The Bytebase service account secret"
    required: true
  auth_client_id:
    description: "The CF auth client ID"
    required: false
  auth_client_secret:
    description: "The CF auth client secret"
    required: false
outputs:
  token:
    description: "The API token obtained from bytebase/login action"
    value: ${{ steps.bytebase-login.outputs.token }}
  api_url:
    description: "The Bytebase API URL with version"
    value: ${{ steps.bytebase-login.outputs.api_url }}
runs:
  using: "composite"
  steps:
    - name: Login
      id: bytebase-login
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/main.sh --url="${{ inputs.bytebase-url }}" --version="${{ inputs.api-version }}" --service-key="${{ inputs.service-key }}" --service-secret="${{ inputs.service-secret }} " --auth_client_id="${{ inputs.auth_client_id }}" --auth_client_secret="${{ inputs.auth_client_secret }}"
branding:
  icon: "database"
  color: "gray-dark"